#!/usr/bin/env python3
"""
Condition Matrix - Pure Code Evaluation for RAG/LLM Answers

Purpose
-------
Compare generated answers against Gold Answers deterministically.

No LLM judge is used.

Input:
    1. answers.json
       Generated by evaluate_llm_nodb_3070ti.py
    2. sarabun-questions100.json
       Gold dataset containing:
           id
           question
           answer

Outputs:
    condition_matrix.json
    condition_matrix.csv
    condition_summary.json

Metrics
-------
1. Answer similarity
   - SequenceMatcher ratio
   - Token F1 against Gold Answer

2. Citation
   - Citation presence
   - Citation validity:
       cited [S#] must exist in retrieved sources
   - Citation precision

3. Grounding heuristic
   - Sentence-level overlap between answer and retrieved Context
   - A sentence is considered "supported" when token overlap with
     the context is >= GROUNDING_THRESHOLD.
   - This is a deterministic heuristic, NOT semantic truth.

4. Hallucination heuristic
   - unsupported sentence ratio
   - Does NOT claim to be a human/LLM semantic hallucination judgment.

5. Overall score
   Default:
       Answer Token F1       50%
       Answer Similarity     20%
       Grounding             20%
       Citation Precision    10%

Important
---------
This is a pure-code Condition Matrix.
It does not use an LLM judge.
Therefore semantic correctness and hallucination are operationalized
using deterministic text-overlap heuristics.
"""

import argparse
import csv
import json
import re
from difflib import SequenceMatcher
from pathlib import Path


# ============================================================
# CONFIG
# ============================================================

DEFAULT_GOLD = (
    Path(__file__).resolve().parent
    / "dataset_for_train"
    / "sarabun-questions100.json"
)

RESULTS_ROOT = Path("/Users/foxixe/Downloads/Test llm /ragtest colab/gemini-ollama-gui/results")

DEFAULT_GOLD = (
    Path(__file__).resolve().parent
    / "dataset_for_train"
    / "sarabun-questions100.json"
)

GROUNDING_THRESHOLD = 0.20

WEIGHTS = {
    "answer_f1": 0.50,
    "answer_similarity": 0.20,
    "grounding": 0.20,
    "citation_precision": 0.10,
}


# ============================================================
# FILE HELPERS
# ============================================================

def load_json(path):
    path = Path(path)
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path, data):
    Path(path).write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


# ============================================================
# DATASET
# ============================================================

def normalize_dataset(data):
    """
    Accept:
        [
            {"id": 1, "question": "...", "answer": "..."}
        ]

    or:
        {"items": [...]}
    """
    if isinstance(data, list):
        items = data
    elif isinstance(data, dict):
        items = data.get("items", [])
    else:
        raise ValueError("Gold dataset must be a list or object with 'items'.")

    if not isinstance(items, list):
        raise ValueError("Gold dataset items must be a list.")

    result = {}

    for item in items:
        if not isinstance(item, dict):
            continue

        item_id = item.get("id")

        if item_id is None:
            continue

        result[str(item_id)] = item

    return result


def load_answers(path):
    data = load_json(path)

    if isinstance(data, dict) and isinstance(data.get("rows"), list):
        return data["rows"]

    if isinstance(data, list):
        return data

    raise ValueError(
        "answers.json must contain a 'rows' list or be a list of answer rows."
    )


# ============================================================
# TEXT NORMALIZATION
# ============================================================

def normalize_text(text):
    if not text:
        return ""

    text = str(text)

    # Remove citation tags.
    text = re.sub(r"\[S\d+\]", " ", text, flags=re.IGNORECASE)

    # Normalize Thai/Arabic numerals to Arabic.
    thai_digits = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_digits)

    # Normalize whitespace.
    text = re.sub(r"\s+", " ", text)

    # Keep Thai characters, Latin characters and digits.
    # Punctuation is treated as separators.
    text = re.sub(
        r"[^\u0E00-\u0E7Fa-zA-Z0-9]+",
        " ",
        text,
    )

    return text.lower().strip()


def tokenize(text):
    """
    Thai text often has no spaces between words.
    We therefore use a character n-gram representation in addition
    to whitespace tokens.

    This function returns normalized character bigrams/trigrams.
    """
    text = normalize_text(text)

    if not text:
        return []

    # Remove spaces for Thai character-level comparison.
    compact = text.replace(" ", "")

    if len(compact) < 2:
        return [compact] if compact else []

    grams = []

    # Character bigrams.
    for i in range(len(compact) - 1):
        grams.append(compact[i:i + 2])

    # Character trigrams.
    for i in range(len(compact) - 2):
        grams.append(compact[i:i + 3])

    return grams


def word_tokens(text):
    text = normalize_text(text)
    return text.split()


# ============================================================
# SIMILARITY
# ============================================================

def sequence_similarity(a, b):
    a = normalize_text(a)
    b = normalize_text(b)

    if not a and not b:
        return 1.0

    if not a or not b:
        return 0.0

    return SequenceMatcher(None, a, b).ratio()


def f1_score(reference, candidate):
    """
    Character n-gram F1.

    This works better than whitespace-token F1 for Thai because
    Thai answers frequently do not contain spaces between words.
    """
    ref = set(tokenize(reference))
    pred = set(tokenize(candidate))

    if not ref and not pred:
        return 1.0

    if not ref or not pred:
        return 0.0

    overlap = len(ref & pred)

    precision = overlap / len(pred)
    recall = overlap / len(ref)

    if precision + recall == 0:
        return 0.0

    return 2 * precision * recall / (precision + recall)


# ============================================================
# CITATIONS
# ============================================================

def extract_citations(answer):
    if not answer:
        return []

    found = re.findall(
        r"\[S(\d+)\]",
        str(answer),
        flags=re.IGNORECASE,
    )

    result = []
    seen = set()

    for number in found:
        citation = f"S{number}"

        if citation not in seen:
            seen.add(citation)
            result.append(citation)

    return result


def parse_sources(value):
    """
    answers.json stores sources as a JSON string.
    Also supports an already-parsed list.
    """
    if not value:
        return []

    if isinstance(value, list):
        return value

    if isinstance(value, str):
        try:
            parsed = json.loads(value)
            return parsed if isinstance(parsed, list) else []
        except json.JSONDecodeError:
            return []

    return []


def citation_metrics(answer, sources):
    citations = extract_citations(answer)

    known = set()

    for source in sources:
        if isinstance(source, dict):
            cid = source.get("citation_id")

            if cid:
                known.add(str(cid).upper())

    valid = [c for c in citations if c.upper() in known]
    invalid = [c for c in citations if c.upper() not in known]

    if citations:
        precision = len(valid) / len(citations)
    else:
        precision = 0.0

    return {
        "citations_found": citations,
        "valid_citations": valid,
        "invalid_citations": invalid,
        "citation_count": len(citations),
        "valid_citation_count": len(valid),
        "invalid_citation_count": len(invalid),
        "citation_precision": round(precision, 4),
        "citation_present": bool(citations),
    }


# ============================================================
# GROUNDING / HALLUCINATION HEURISTIC
# ============================================================

def split_sentences(text):
    if not text:
        return []

    text = str(text).strip()

    # Thai/English sentence boundaries.
    parts = re.split(
        r"(?<=[.!?。！？])\s+|\n+",
        text,
    )

    return [p.strip() for p in parts if p.strip()]


def overlap_with_context(sentence, context):
    sentence_tokens = set(tokenize(sentence))
    context_tokens = set(tokenize(context))

    if not sentence_tokens:
        return 1.0

    if not context_tokens:
        return 0.0

    overlap = len(sentence_tokens & context_tokens)

    return overlap / len(sentence_tokens)


def grounding_metrics(answer, context):
    sentences = split_sentences(answer)

    # If answer has no sentence punctuation, treat whole answer as one claim.
    if not sentences and answer:
        sentences = [answer]

    if not sentences:
        return {
            "claim_count": 0,
            "supported_claim_count": 0,
            "unsupported_claim_count": 0,
            "grounding_score": 0.0,
            "unsupported_claim_ratio": 0.0,
            "claims": [],
        }

    claims = []
    supported = 0

    for index, sentence in enumerate(sentences, 1):
        overlap = overlap_with_context(sentence, context)

        is_supported = overlap >= GROUNDING_THRESHOLD

        if is_supported:
            supported += 1

        claims.append(
            {
                "claim_no": index,
                "text": sentence,
                "context_overlap": round(overlap, 4),
                "supported": is_supported,
            }
        )

    unsupported = len(sentences) - supported

    grounding_score = supported / len(sentences)
    unsupported_ratio = unsupported / len(sentences)

    return {
        "claim_count": len(sentences),
        "supported_claim_count": supported,
        "unsupported_claim_count": unsupported,
        "grounding_score": round(grounding_score, 4),
        "unsupported_claim_ratio": round(unsupported_ratio, 4),
        "claims": claims,
    }


# ============================================================
# CONDITION MATRIX
# ============================================================

def condition_score(answer_f1, answer_similarity, grounding, citation_precision):
    score = (
        answer_f1 * WEIGHTS["answer_f1"]
        + answer_similarity * WEIGHTS["answer_similarity"]
        + grounding * WEIGHTS["grounding"]
        + citation_precision * WEIGHTS["citation_precision"]
    )

    return round(score * 100, 2)


def condition_label(score):
    if score >= 90:
        return "EXCELLENT"

    if score >= 80:
        return "GOOD"

    if score >= 70:
        return "ACCEPTABLE"

    if score >= 60:
        return "WEAK"

    return "POOR"


# ============================================================
# EVALUATE ONE ROW
# ============================================================

def evaluate_row(row, gold_item):
    answer = row.get("answer", "")
    question = row.get("question", "")

    if gold_item is None:
        return {
            "id": row.get("id"),
            "question": question,
            "model": row.get("model"),
            "status": "MISSING_GOLD",
            "gold_answer": "",
            "answer": answer,
            "answer_similarity": None,
            "answer_f1": None,
            "citation_present": bool(extract_citations(answer)),
            "citation_precision": None,
            "grounding_score": None,
            "unsupported_claim_ratio": None,
            "overall_score": None,
            "condition": "NOT_SCORED",
            "reason": "No Gold Answer found for this ID.",
        }

    gold_answer = gold_item.get("answer", "")

    similarity = sequence_similarity(gold_answer, answer)
    answer_f1 = f1_score(gold_answer, answer)

    sources = parse_sources(row.get("sources"))
    citations = citation_metrics(answer, sources)

    grounding = grounding_metrics(
        answer,
        row.get("context", ""),
    )

    score = condition_score(
        answer_f1=answer_f1,
        answer_similarity=similarity,
        grounding=grounding["grounding_score"],
        citation_precision=citations["citation_precision"],
    )

    return {
        "id": row.get("id"),
        "question": question,
        "model": row.get("model"),

        "status": "SCORED",

        "gold_answer": gold_answer,
        "answer": answer,

        "answer_similarity": round(similarity, 4),
        "answer_f1": round(answer_f1, 4),

        "citation_present": citations["citation_present"],
        "citations_found": citations["citations_found"],
        "valid_citations": citations["valid_citations"],
        "invalid_citations": citations["invalid_citations"],
        "citation_precision": citations["citation_precision"],

        "claim_count": grounding["claim_count"],
        "supported_claim_count": grounding["supported_claim_count"],
        "unsupported_claim_count": grounding["unsupported_claim_count"],
        "grounding_score": grounding["grounding_score"],
        "unsupported_claim_ratio": grounding["unsupported_claim_ratio"],

        "overall_score": score,
        "condition": condition_label(score),

        "latency_ms": row.get("latency_ms"),
        "prompt_tokens": row.get("prompt_tokens"),
        "output_tokens": row.get("output_tokens"),
        "total_tokens": row.get("total_tokens"),
    }


# ============================================================
# SUMMARY
# ============================================================

def average(values):
    values = [v for v in values if isinstance(v, (int, float))]

    if not values:
        return None

    return round(sum(values) / len(values), 4)


def build_summary(results, answers_data, gold):
    scored = [
        r for r in results
        if r.get("status") == "SCORED"
    ]

    missing = [
        r for r in results
        if r.get("status") == "MISSING_GOLD"
    ]

    scores = [r["overall_score"] for r in scored]
    f1s = [r["answer_f1"] for r in scored]
    similarities = [r["answer_similarity"] for r in scored]
    grounding = [r["grounding_score"] for r in scored]
    citation_precision = [
        r["citation_precision"] for r in scored
    ]
    hallucination_ratio = [
        r["unsupported_claim_ratio"] for r in scored
    ]

    condition_counts = {}

    for row in scored:
        label = row["condition"]
        condition_counts[label] = condition_counts.get(label, 0) + 1

    return {
        "model": answers_data.get("model"),

        "dataset": {
            "answers_rows": len(answers_data.get("rows", [])),
            "gold_items": len(gold),
            "scored": len(scored),
            "missing_gold": len(missing),
            "generation_errors": len(
                answers_data.get("errors_detail", [])
            ),
        },

        "metrics": {
            "overall_score_0_100": average(scores),
            "answer_f1": average(f1s),
            "answer_similarity": average(similarities),
            "grounding_score": average(grounding),
            "citation_precision": average(citation_precision),

            # Heuristic only.
            "unsupported_claim_ratio": average(
                hallucination_ratio
            ),
        },

        "condition_distribution": condition_counts,

        "weights": {
            "answer_f1": WEIGHTS["answer_f1"],
            "answer_similarity": WEIGHTS["answer_similarity"],
            "grounding": WEIGHTS["grounding"],
            "citation_precision": WEIGHTS["citation_precision"],
        },

        "grounding_threshold": GROUNDING_THRESHOLD,

        "interpretation": {
            "method": "pure_code",
            "llm_judge": False,
            "hallucination_metric": (
                "unsupported_claim_ratio based on deterministic "
                "answer-context character n-gram overlap; "
                "not a semantic hallucination judgment"
            ),
        },
    }


# ============================================================
# MAIN
# ============================================================

def choose_results_folder():
    """Open a folder chooser starting at the project's results directory."""
    try:
        import tkinter as tk
        from tkinter import filedialog

        root = tk.Tk()
        root.withdraw()
        root.attributes("-topmost", True)

        initial_dir = RESULTS_ROOT if RESULTS_ROOT.is_dir() else Path.home()

        folder = filedialog.askdirectory(
            title="เลือกโฟลเดอร์ผลลัพธ์ที่ต้องการประเมิน",
            initialdir=str(initial_dir),
            mustexist=True,
        )

        root.destroy()

        if not folder:
            raise SystemExit("ยกเลิกการเลือกโฟลเดอร์")

        return Path(folder).expanduser().resolve()

    except ImportError as exc:
        raise RuntimeError(
            "ไม่สามารถเปิดหน้าต่างเลือกโฟลเดอร์ได้ เนื่องจากไม่มี tkinter"
        ) from exc


def main():
    parser = argparse.ArgumentParser(
        description="Pure-code Condition Matrix - เลือกโฟลเดอร์ answers จาก results ตอนรัน"
    )

    parser.add_argument(
        "--gold",
        default=str(DEFAULT_GOLD),
        help="Path to Gold dataset JSON (default: project/scripts/dataset_for_train/sarabun-questions100.json)",
    )

    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory (default: answers folder/condition_matrix)",
    )

    parser.add_argument(
        "--answers",
        default=None,
        help="Path to answers.json. If omitted, a folder is selected interactively from results/.",
    )

    args = parser.parse_args()

    # If --answers is supplied, use it directly. Otherwise select a result
    # subfolder interactively from the configured results directory.
    if args.answers:
        answers_path = Path(args.answers).expanduser().resolve()
        selected_folder = answers_path.parent
    else:
        selected_folder = choose_results_folder()
        answers_path = selected_folder / "answers.json"
    gold_path = Path(args.gold).expanduser().resolve()

    if not answers_path.is_file():
        raise FileNotFoundError(
            f"ไม่พบ answers.json: {answers_path}"
        )

    if not gold_path.is_file():
        raise FileNotFoundError(
            f"ไม่พบ Gold dataset: {gold_path}"
        )

    answers_data = load_json(answers_path)
    rows = load_answers(answers_path)

    gold_data = load_json(gold_path)
    gold = normalize_dataset(gold_data)

    if args.output_dir:
        output_dir = Path(args.output_dir).expanduser().resolve()
    else:
        output_dir = answers_path.parent / "condition_matrix"

    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print("CONDITION MATRIX - PURE CODE")
    print("=" * 70)
    print(f"Selected: {selected_folder}")
    print(f"Answers : {answers_path}")
    print(f"Gold    : {gold_path}")
    print(f"Rows    : {len(rows)}")
    print(f"Gold    : {len(gold)}")
    print(f"Output  : {output_dir}")
    print("=" * 70)

    results = []

    for index, row in enumerate(rows, 1):
        item_id = str(row.get("id"))

        gold_item = gold.get(item_id)

        result = evaluate_row(
            row=row,
            gold_item=gold_item,
        )

        results.append(result)

        if result["status"] == "SCORED":
            print(
                f"[{index}/{len(rows)}] "
                f"id={item_id} "
                f"score={result['overall_score']} "
                f"{result['condition']}",
                flush=True,
            )
        else:
            print(
                f"[{index}/{len(rows)}] "
                f"id={item_id} "
                f"MISSING_GOLD",
                flush=True,
            )

    summary = build_summary(
        results,
        answers_data,
        gold,
    )

    output_json = output_dir / "condition_matrix.json"
    output_csv = output_dir / "condition_matrix.csv"
    summary_json = output_dir / "condition_summary.json"

    output_data = {
        "method": "pure_code_condition_matrix",
        "source_answers": str(answers_path),
        "source_gold": str(gold_path),
        "weights": WEIGHTS,
        "grounding_threshold": GROUNDING_THRESHOLD,
        "summary": summary,
        "results": results,
    }

    save_json(output_json, output_data)
    save_json(summary_json, summary)

    csv_fields = [
        "id",
        "question",
        "model",
        "status",
        "answer_similarity",
        "answer_f1",
        "citation_present",
        "citations_found",
        "valid_citations",
        "invalid_citations",
        "citation_precision",
        "claim_count",
        "supported_claim_count",
        "unsupported_claim_count",
        "grounding_score",
        "unsupported_claim_ratio",
        "overall_score",
        "condition",
        "latency_ms",
        "prompt_tokens",
        "output_tokens",
        "total_tokens",
    ]

    with output_csv.open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=csv_fields,
        )

        writer.writeheader()

        for row in results:
            writer.writerow(
                {
                    field: (
                        json.dumps(
                            row.get(field),
                            ensure_ascii=False,
                        )
                        if isinstance(
                            row.get(field),
                            (list, dict),
                        )
                        else row.get(field)
                    )
                    for field in csv_fields
                }
            )

    print("\n" + "=" * 70)
    print("CONDITION MATRIX SUMMARY")
    print("=" * 70)

    print(
        f"Scored                  : "
        f"{summary['dataset']['scored']}"
    )

    print(
        f"Missing Gold            : "
        f"{summary['dataset']['missing_gold']}"
    )

    print(
        f"Overall Score           : "
        f"{summary['metrics']['overall_score_0_100']}"
    )

    print(
        f"Answer F1               : "
        f"{summary['metrics']['answer_f1']}"
    )

    print(
        f"Answer Similarity       : "
        f"{summary['metrics']['answer_similarity']}"
    )

    print(
        f"Grounding Score         : "
        f"{summary['metrics']['grounding_score']}"
    )

    print(
        f"Citation Precision      : "
        f"{summary['metrics']['citation_precision']}"
    )

    print(
        f"Unsupported Claim Ratio : "
        f"{summary['metrics']['unsupported_claim_ratio']}"
    )

    print(
        f"Distribution             : "
        f"{summary['condition_distribution']}"
    )

    print("\nFiles:")
    print(f"  {output_json}")
    print(f"  {output_csv}")
    print(f"  {summary_json}")
    print("=" * 70)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
